### ISSUE TITLE
failed to compile on windows vs2017

### ISSUE THREAD

**Issue by BigPandaCPU** [MyEvolution/Dragon#1]
Failed to compile on windows with VS2017.the error message is below

1>D:\project\VSProject\Dragon-main\3rdparty\imgui\imgui_impl_opengl3.h(61): fatal error C1189: #error:  "Cannot detect OpenGL loader!"

Only support linux?

**Comment by wlsdzyzl** [comment]
Currently i only tested on Ubuntu. And now i don't have time to do some extra work on windows compilation. Sorry for this!
